<?php

use Fisharebest\Webtrees\View;

?>

<?php View::push('javascript') ?>
<script>
    // Detect browser screen width and store it in a session cookie
    // https://www.w3schools.com/js/js_cookies.asp
    // https://stackoverflow.com/questions/14196671/session-only-cookies-with-javascript
    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value
    function setCookie(cname, cvalue) {
        if (window.location.protocol == 'http:') {
            document.cookie = cname + "=" + cvalue + ";path=/;SameSite=Lax";
        } else {
            document.cookie = cname + "=" + cvalue + ";path=/;SameSite=Lax;Secure";
        }
    }

    function getCookie(cname) {
        let name = cname + "=";
        let ca = document.cookie.split(';');
        for(let i = 0; i < ca.length; i++) {
            let c = ca[i];
            while (c.charAt(0) === ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    if (window.innerWidth !== getCookie("FIB_WIDTH")) {
        setCookie("FIB_WIDTH", window.innerWidth);
    }

    // Script to keep map coords and images in sync
    function mapcoords() {
        var height = $('.jc-fancy-imagebar img').height(); // current height of the imagebar
        var setting = $('.jc-fancy-imagebar').attr('data-height'); // original height (from the settings in control panel)
        var ratio = height / setting
        $('.jc-fancy-imagebar-map area').each(function() {
            // save the original coords
            if (!$(this).attr('data-coords')) {
                $(this).attr('data-coords', $(this).attr('coords'));
            }
            var coords = $(this).attr('data-coords').split(', ');
            var new_coords = [];
            new_coords[0] = parseInt(coords[0]) * ratio;
            new_coords[1] = parseInt(coords[1]);
            new_coords[2] = parseInt(coords[2]) * ratio;
            new_coords[3] = parseInt(coords[3]);
            $(this).attr("coords", new_coords.join(', '));
        });
    }

    // Map coordinates as soon as html is parsed, so that data-coords can be stored in area
    document.addEventListener('DOMContentLoaded', mapcoords);

    // Listen for window resizing
    $(window).resize(function() {
        if (window.innerWidth !== getCookie("FIB_WIDTH")) {
            setCookie("FIB_WIDTH", window.innerWidth);
            mapcoords();
        }
    });   
</script>
<?php View::endpush() ?>
