<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<p class="alert alert-info">
    <?= I18N::translate('Choose the images for the Fancy Imagebar. If there are fewer images chosen than needed to fill up the entire Fancy Imagebar, the images will be repeated.') ?>
    <?= I18N::translate('Note: Only local “jpg” or “png” images are supported by this module. External images are not supported. It is not possible to keep transparency for png thumbnails in the Fancy Imagebar. Transparent png-thumbnails will get a black background in the Fancy Imagebar. The images shown in this table have the right specifications already.') ?>
    <?= I18N::translate('The Fancy Imagebar module respects privacy settings!') ?>
</p>

<?php // not converted parts of form commented out in php tags to test the other parts ?>
<form method="post">
    <?= csrf_field() ?>
    <div class="card mb-4">
        <div class="card-header">
            <h2 class="mb-0">
                <?= I18N::translate('Settings') ?>
            </h2>
        </div>
        <div class="card-body">
            <!-- TREE LIST -->
            <div class="row form-group">
                <label class="col-sm-3 col-form-label for=" tree"><?= I18N::translate('Family tree') ?></label>
                <div class="col-sm-9">
                    <select class="form-control" id="tree" name="tree" type="text" required>
                        <option value=""><?= I18N::translate('&lt;select&gt;') ?></option>
                        <?php foreach ($all_trees as $tree) : ?>
                        <option value="<?= $tree->name() ?>">
                            <?= $tree->title() ?>
                        </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            <!-- MEDIA FOLDER LIST -->
            <div class="row form-group">
                <label class="col-sm-3 col-form-label" for="media-folder">
                    <?= I18N::translate('Media folder') ?>
                </label>
                <div class="col-sm-9">
                    <select class="form-control" id="media-folder" name="media-folder" type="text" required>
                        <option value=""><?= I18N::translate('&lt;select&gt;') ?></option>
                        <?php foreach ($media_folders as $media_folder) : ?>
                        <option value="<?= $media_folder ?>" <?= $media_folder_selected === $media_folder ? 'selected' : '' ?>>
                            <?= $media_folder ?>
                        </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            <!-- MEDIA TYPE LIST -->
            <div class="row form-group">
                <label class="col-sm-3 col-form-label" for="media-type">
                    <?= I18N::translate('Media type') ?>
                </label>
                <div class="col-sm-9">
                    <select class="form-control" id="media-type" name="media-type" type="text" required>
                        <option value=""><?= I18N::translate('&lt;select&gt;') ?></option>
                        <?php foreach ($media_types as $media_type => $media_type_name) : ?>
                        <option value="<?= $media_type ?>" <?= $media_type_selected === $media_type ? 'selected' : '' ?>>
                            <?= $media_type_name ?>
                        </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            <!-- HEIGHT OF THE IMAGE BAR -->
            <div class="row form-group">
                <label class="col-form-label col-sm-3">
                    <?= I18N::translate('Height of the Fancy Imagebar') ?>
                </label>
                <div class="col-sm-1">
                    <input class="form-control" type="text" name="canvas-height" size="3" value="<?= $canvas_height ?>">
                </div>
                <div class="form-control-static align-self-center">px</div>
            </div>
            <!-- CROP THUMBNAILS TO SQUARE -->
            <fieldset class="form-group">
                <div class="row">
                    <legend class="col-form-label col-sm-3">
                        <?= I18N::translate('Use square thumbnails') ?>
                    </legend>
                    <div class="col-sm-9">
                        <?= view('components/radios-inline', ['name' => 'square-thumbs', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => $square_thumbs]) ?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">
        <?= view('icons/save') ?>
        <?= I18N::translate('save') ?>
    </button>
</form>
